### ISSUE TITLE
nodejs-ffi库需要更换

### ISSUE THREAD

**Issue by cutrain** [cutrain/VisualDataPlatform#4]
如果动态链接库里面调用了其他的动态链接库，nodejs-ffi无法完成symbol映射。需要换种方式和c++交互

**Comment by lzmhhh123** [comment]
你本地的node版本和ffi版本是多少？

**Comment by cutrain** [comment]
ffi是2.2.0
node是v0.10.48，不过在ffi上面说的0.10测试过，应该不是版本问题。

**Comment by cutrain** [comment]
在我刚刚push的那个分支上你可以试下。按readme里面写的make一个，然后运行./algorithm/test/main.js会报undefined symbol。是libboost_system里面的符号，很奇怪的是，我就算换成静态连接的boost库也会报这个问题。

**Comment by lzmhhh123** [comment]
我的環境是nodev9.20，嘗試了一下，ffi安裝貌似有問題，參考https://github.com/node-ffi/node-ffi/issues/438，這個庫貌似一年來只有一個commit，也有很多問題沒有解決。

**Comment by lzmhhh123** [comment]
如果實在不行，那就只有換後端的語言了，分佈式可擴展性好的話可以用go，簡單一點可以直接上python的django

**Comment by cutrain** [comment]
抱歉，我之前傻了。刚才又查了以下symbol表，发现生成的so文件里面符号表确实没有定义，看来是boost的链接方式不正确，我再看看。

**Comment by cutrain** [comment]
我是降到0.10才装上ffi的...过两天我们再看下这个库能不能用到v9上把，不行就换了

**Comment by cutrain** [comment]
把`$(CC) -shared -fPIC $(LIBS) main.cc`改成`$(CC) -shared -fPIC main.cc $(LIBS)`就找到链接了。
链接顺序真是神奇。。。
